export const customMacros: Record<string, string> = {
  // Caligraphic letters
  "\\calA": "\\mathcal{A}",
  "\\calB": "\\mathcal{B}",
  "\\calC": "\\mathcal{C}",
  "\\calD": "\\mathcal{D}",
  "\\calE": "\\mathcal{E}",
  "\\calF": "\\mathcal{F}",
  "\\calG": "\\mathcal{G}",
  "\\calH": "\\mathcal{H}",
  "\\calI": "\\mathcal{I}",
  "\\calJ": "\\mathcal{J}",
  "\\calK": "\\mathcal{K}",
  "\\calL": "\\mathcal{L}",
  "\\calM": "\\mathcal{M}",
  "\\calN": "\\mathcal{N}",
  "\\calO": "\\mathcal{O}",
  "\\calP": "\\mathcal{P}",
  "\\calQ": "\\mathcal{Q}",
  "\\calR": "\\mathcal{R}",
  "\\calS": "\\mathcal{S}",
  "\\calT": "\\mathcal{T}",
  "\\calU": "\\mathcal{U}",
  "\\calV": "\\mathcal{V}",
  "\\calW": "\\mathcal{W}",
  "\\calX": "\\mathcal{X}",
  "\\calY": "\\mathcal{Y}",
  "\\calZ": "\\mathcal{Z}",
  // Complexity classes
  "\\classP": "\\mathbf{P}",
  "\\classNP": "\\mathbf{NP}",
  "\\classcoNP": "\\mathbf{coNP}",
  "\\classBPP": "\\mathbf{BPP}",
  "\\classRP": "\\mathbf{RP}",
  "\\classZPP": "\\mathbf{ZPP}",
  "\\classPSPACE": "\\mathbf{PSPACE}",
  "\\classSZK": "\\mathbf{SZK}",
  "\\classCZK": "\\mathbf{CZK}",
  "\\classIP": "\\mathbf{IP}",
  "\\classAM": "\\mathbf{AM}",
  "\\classMA": "\\mathbf{MA}",
  "\\classcoAM": "\\mathbf{coAM}",
  "\\classPP": "\\mathbf{PP}",
  "\\classPpoly": "\\mathbf{P/poly}",
  "\\classEXP": "\\mathbf{EXP}",
  "\\classTFNP": "\\mathbf{TFNP}",
  "\\classsharpP": "\\mathbf{\\#P}",
  "\\classBQP": "\\mathbf{BQP}",
  "\\classQMA": "\\mathbf{QMA}",
  "\\classQCMA": "\\mathbf{QCMA}",
  "\\classQIP": "\\mathbf{QIP}",
  "\\classQSZK": "\\mathbf{QSZK}",
  // Common algorithms
  "\\Gen": "\\mathsf{Gen}",
  "\\GrGen": "\\mathsf{GrGen}",
  "\\KeyGen": "\\mathsf{KeyGen}",
  "\\Enc": "\\mathsf{Enc}",
  "\\Dec": "\\mathsf{Dec}",
  "\\Setup": "\\mathsf{Setup}",
  "\\Query": "\\mathsf{Query}",
  "\\Eval": "\\mathsf{Eval}",
  "\\Invert": "\\mathsf{Invert}",
  "\\Sign": "\\mathsf{Sign}",
  "\\Vrfy": "\\mathsf{Vrfy}",
  "\\Tag": "\\mathsf{Tag}",
  "\\Answer": "\\mathsf{Answer}",
  "\\Decode": "\\mathsf{Decode}",
  "\\Extract": "\\mathsf{Extract}",
  "\\Delegate": "\\mathsf{Delegate}",
  // Number sets
  "\\NN": "\\mathbb{N}",
  "\\ZZ": "\\mathbb{Z}",
  "\\FF": "\\mathbb{F}",
  "\\GG": "\\mathbb{G}",
  // Simulators and state
  "\\Sim": "\\mathcal{S}",
  "\\st": "\\mathsf{st}",
  "\\stA": "\\mathsf{st}_{\\mathcal{A}}",
  "\\stB": "\\mathsf{st}_{\\mathcal{B}}",
  "\\stS": "\\mathsf{st}_{\\mathcal{S}}",
  "\\View": "\\mathsf{V}",
  // Variable names
  "\\pp": "\\mathsf{pp}",
  "\\crs": "\\mathsf{crs}",
  "\\sk": "\\mathsf{sk}",
  "\\pk": "\\mathsf{pk}",
  "\\vk": "\\mathsf{vk}",
  "\\td": "\\mathsf{td}",
  "\\msk": "\\mathsf{msk}",
  "\\mpk": "\\mathsf{mpk}",
  // Crypto shorthand
  "\\bits": "\\{0,1\\}",
  "\\negl": "\\mathrm{negl}",
  "\\poly": "\\mathrm{poly}",
  "\\polylog": "\\mathrm{polylog}",
  "\\PPT": "\\mathrm{PPT}",
  "\\secpar": "\\lambda",
  "\\getsr": "\\overset{\\$}{\\gets}",
  "\\Funcs": "\\mathrm{Funcs}",
  "\\Perms": "\\mathrm{Perms}",
  // Advantages and experiments
  "\\Adv": "\\mathbf{Adv}",
  "\\Expt": "\\mathbf{Expt}",
  "\\Game": "\\mathbf{G}",
  // Game names
  "\\indcpa": "\\mathrm{ind\\text{-}cpa}",
  "\\indcca": "\\mathrm{ind\\text{-}cca}",
  "\\ufcma": "\\mathrm{uf\\text{-}cma}",
  "\\eufcma": "\\mathrm{euf\\text{-}cma}",
  "\\sufcma": "\\mathrm{suf\\text{-}cma}",
  // Select Primitives
  "\\PRF": "\\mathsf{PRF}",
  "\\RO": "\\mathsf{RO}",
  "\\PRG": "\\mathsf{PRG}",
  "\\PRP": "\\mathsf{PRP}",
  "\\OT": "\\mathsf{OT}",
  "\\SKE": "\\mathsf{SKE}",
  "\\PKE": "\\mathsf{PKE}",
  "\\DS": "\\mathsf{DS}",
  "\\MAC": "\\mathsf{MAC}",
  "\\PIR": "\\mathsf{PIR}",
  "\\hash": "\\mathsf{H}",
  "\\IBE": "\\mathsf{IBE}",
  "\\HIBE": "\\mathsf{HIBE}",
  "\\ABE": "\\mathsf{ABE}",
};
