import test, { describe } from "node:test";
import assert from "node:assert";
import {
  parseBib,
  formatBibtex,
  normalizeAuthors,
  normalizeForCompare,
  stripBibBraces,
} from "./cryptobib";

const SAMPLE = `
% File generated by gen.py

@string{crypto01name = "Advances in Cryptology -- {CRYPTO}~2001"}
@string{crypto01ed = "Joe Kilian"}
@string{mylncs = "Lecture Notes in Computer Science"}

@InProceedings{C:BonFra01,
  author =       "Dan Boneh and
                  Matthew K. Franklin",
  title =        "Identity-Based Encryption from the {Weil} Pairing",
  pages =        "213--229",
  editor =       crypto01ed,
  booktitle =    crypto01name,
  series =       mylncs,
  year =         2001,
  doi =          "10.1007/3-540-44647-8_13",
}

@Misc{EPRINT:BonFra01,
  author =       "Dan Boneh and Matthew K. Franklin",
  title =        "Identity-Based Encryption from the {Weil} Pairing",
  year =         2001,
  howpublished = "Cryptology {ePrint} Archive, Report 2001/090",
  url =          "https://eprint.iacr.org/2001/090",
}
`;

describe("cryptobib parser", () => {
  test("parses string macros and expands them in entries", () => {
    const db = parseBib(SAMPLE);
    assert.strictEqual(db.strings.get("crypto01ed"), "Joe Kilian");
    const entry = db.entries.get("C:BonFra01");
    assert.ok(entry);
    assert.strictEqual(entry!.type, "inproceedings");
    assert.strictEqual(entry!.fields.editor, "Joe Kilian");
    assert.strictEqual(
      entry!.fields.booktitle,
      "Advances in Cryptology -- {CRYPTO}~2001",
    );
    assert.strictEqual(
      entry!.fields.series,
      "Lecture Notes in Computer Science",
    );
    assert.strictEqual(entry!.fields.year, "2001");
  });

  test("preserves brace-protection in titles", () => {
    const db = parseBib(SAMPLE);
    const entry = db.entries.get("C:BonFra01")!;
    assert.strictEqual(
      entry.fields.title,
      "Identity-Based Encryption from the {Weil} Pairing",
    );
  });

  test("handles multi-line author fields", () => {
    const db = parseBib(SAMPLE);
    const entry = db.entries.get("C:BonFra01")!;
    assert.match(entry.fields.author, /Dan Boneh and\s+Matthew K\. Franklin/);
  });

  test("formatBibtex produces a self-contained block in canonical field order", () => {
    const db = parseBib(SAMPLE);
    const entry = db.entries.get("C:BonFra01")!;
    const out = formatBibtex(entry);
    assert.match(out, /^@Inproceedings\{C:BonFra01,/);
    // editor must be expanded, not the macro name
    assert.match(out, /editor = \{Joe Kilian\},/);
    // ordering: author should appear before booktitle
    assert.ok(out.indexOf("author = ") < out.indexOf("booktitle = "));
  });

  test("normalizeAuthors converts BibTeX 'and' to comma list", () => {
    const got = normalizeAuthors("Dan Boneh and Matthew K. Franklin");
    assert.strictEqual(got, "Dan Boneh, Matthew K. Franklin");
  });

  test("normalizeAuthors handles 'Last, First' form", () => {
    const got = normalizeAuthors("Boneh, Dan and Franklin, Matthew K.");
    assert.strictEqual(got, "Dan Boneh, Matthew K. Franklin");
  });

  test("stripBibBraces removes brace protection", () => {
    assert.strictEqual(
      stripBibBraces("Identity-Based Encryption from the {Weil} Pairing"),
      "Identity-Based Encryption from the Weil Pairing",
    );
  });

  test("normalizeForCompare lowercases and strips punctuation", () => {
    assert.strictEqual(
      normalizeForCompare("Identity-Based Encryption from the {Weil} Pairing"),
      "identity based encryption from the weil pairing",
    );
  });

  test("ignores @comment and @preamble blocks", () => {
    const db = parseBib(`
      @preamble{"\\\\newcommand{\\\\foo}{bar}"}
      @comment{this is a comment}
      @InProceedings{X:Y, author = "A B", title = "T", year = 2020,}
    `);
    assert.strictEqual(db.entries.size, 1);
    assert.ok(db.entries.has("X:Y"));
  });

  test("merges into an existing database (used to load abbrev*.bib then crypto.bib)", () => {
    const db = parseBib(`@string{venue = "Some Venue"}`);
    parseBib(`@InProceedings{K, booktitle = venue, year = 2024,}`, db);
    assert.strictEqual(db.entries.get("K")!.fields.booktitle, "Some Venue");
  });
});
